# Generated by Django 6.1.1 on 2026-09-28 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=100)),
                ('fecha_hora', models.DateTimeField(max_length=100)),
                ('autor', models.CharField(max_length=25)),
            ],
            options={
                'db_table_comment': 'Tabla de los comentarios creados por los usuarios.',
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id_entrada', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField()),
                ('visibilidad', models.BooleanField(default=True)),
                ('estado', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table_comment': 'Tabla de las entradas creadas por los usuarios.',
            },
        ),
    ]
